# Generated by Django 6.0.7 on 2026-09-06 21:37

import pedidos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_actualizado_pedido_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disenopedido',
            name='imagen',
            field=models.ImageField(storage=pedidos.storage.diseno_storage, upload_to='disenos/%Y/%m/'),
        ),
    ]
