# Generated by Django 6.0.7 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_facturacion',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion_facturacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='razon_social',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='usuario',
            name='referencia_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
