# Generated by Django 6.0.7 on 2026-09-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='latitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='precision_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
