# Generated by Django 6.0.7 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_initial'),
        ('productos', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_diseno',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_entrega_deseada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
