# Generated by Django 6.0.7 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('cotizaciones', '0004_cotizacion_aprobacion')]

    operations = [
        migrations.CreateModel(
            name='ArchivoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cotizaciones/%Y/%m/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Archivo de cotización',
                'verbose_name_plural': 'Archivos de cotización',
                'ordering': ['fecha_carga'],
            },
        ),
    ]
