# Generated by Django 6.0.7 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('cotizaciones', '0005_archivocotizacion')]

    operations = [
        migrations.AddField(model_name='cotizacion', name='es_urgente', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='cotizacion', name='fecha_entrega_programada', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='cotizacion', name='motivo_urgencia', field=models.CharField(blank=True, max_length=255)),
    ]
