# Generated by Django 6.0.7 on 2026-09-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_cotizacion_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones',
            field=models.TextField(default='Producción sujeta a aprobación del precio y del diseño. Entrega según agenda confirmada.'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valida_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
