# Generated by Django 6.0.7 on 2026-09-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_controlagenda_cotizacion_condiciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocotizacion',
            name='huella',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='archivocotizacion',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'huella'), name='imagen_unica_por_cotizacion'),
        ),
    ]
