platform :ios, '15.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', { 'Debug' => :debug, 'Profile' => :release, 'Release' => :release }

def flutter_root
  config = File.expand_path(File.join('Flutter', 'Generated.xcconfig'), __dir__)
  raise 'Run flutter pub get first' unless File.exist?(config)
  File.foreach(config) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise 'FLUTTER_ROOT not found'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup
target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      if target.name == 'permission_handler_apple'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] += [
          'PERMISSION_CAMERA=1', 'PERMISSION_LOCATION=0',
          'PERMISSION_LOCATION_WHENINUSE=1', 'PERMISSION_PHOTOS=0',
          'PERMISSION_MICROPHONE=0', 'PERMISSION_NOTIFICATIONS=0'
        ]
      end
      if target.name == 'geolocator_apple'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] += ['BYPASS_PERMISSION_LOCATION_ALWAYS=1']
      end
    end
  end
end
